config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#index'
  get '/faq', to: 'pages#faq'
  get '/contacts', to: 'contacts#new'
  resources 'contacts', only: %i[new create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < MailForm::Base
  attribute :name,      validate: true
  attribute :email,     validate: /\A[^@\s]+@[^@\s]+\z/i
  attribute :message
  attribute :nickname, captcha: true

  def headers
    {
      subject: 'My Contact Form',
      to: 'your.email@your.domain.com',
      from: %('#{name}' <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'OK'
    else
      flash.now[:error] = 'NOK'
      render :new
    end
  end
end

app/controllers/frontends_controller.rb
class FrontendsController < ApplicationController

  def frontend
  end

end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end

  def faq; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <h1>Contact</h1>
        <div class="controls">
          <%= form_with do |form| %>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                  <%= form.label :username, "Username :" %>
                  <%= form.text_field :username, class: "form-control" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                  <%= form.label :email, "Email :" %>
                  <%= form.text_field :email, class: "form-control" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                  <%= form.label :message, "Message :" %>
                  <%= form.text_area :message, class: "form-control", rows: 5 %>
              </div>
            </div>
            <div class="col-md-12">
                <%= form.submit "Send message", class: "btn btn-success btn-send" %>
            </div>
          </div>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/frontends/frontend.html.erb
<h1>test</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minekosan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render partial: 'layouts/parts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/parts/_navbar.html.erb
<header>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-dark border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">
      <%= link_to "MinekoSan", root_path, class: "text-white" %>
    </h5>
    <nav class="my-2 my-md-0 mr-md-3">
      <a class="p-2 text-white" href="#">Portfolio</a>
      <a class="p-2 text-white" href="#">Shop</a>
      <%= link_to "FAQ", faq_path, class: "p-2 text-white" %>
    </nav>
    <%= link_to "Contact", contacts_path, class: "btn btn-outline-primary" %>
  </div>
</header>

app/views/pages/faq.html.erb
<div class="container">
  <div class="d-flex align-items-start flex-column bd-highlight mb-3" style="height: 200px;">
    <div class="p-1 bd-highlight">
      <h2>Toto</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur cupiditate ducimus est eum nobis? Ab amet aperiam, atque eveniet, ex expedita in libero magni modi officia perspiciatis quae tempore tenetur?</p>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<main role="main">

  <div class="container">
    <div class="d-flex flex-row bd-highlight mb-3">
      <div class="p-2 bd-highlight">
        <%= image_tag 'http://placekitten.com/300/500' %>
      </div>
      <div class="p-2 bd-highlight align-self-center">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci delectus, est ex illum itaque libero maxime nemo, non officiis possimus quae quia quod repellat rerum soluta ullam vel? Iste, modi.</p>
      </div>
    </div>
    <div class="d-flex flex-row bd-highlight mb-3">
      <div class="p-2 bd-highlight align-self-center">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci delectus, est ex illum itaque libero maxime nemo, non officiis possimus quae quia quod repellat rerum soluta ullam vel? Iste, modi.</p>
      </div>
      <div class="p-2 bd-highlight">
        <%= image_tag 'http://placekitten.com/300/500' %>
      </div>
    </div>
    <div class="d-flex flex-row bd-highlight mb-3">
      <div class="p-2 bd-highlight align-self-center text-center">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci delectus, est ex illum itaque libero maxime nemo, non officiis possimus quae quia quod repellat rerum soluta ullam vel? Iste, modi.</p>
      </div>
    </div>
    <div class="d-flex justify-content-center">
        <%= image_tag 'http://placekitten.com/1000/300', style: 'align-center' %>
    </div>
  </div>
</main>